version: "3.7"
services:
  api:
    image: gcr.io/aspen-lang/platform/api:${API_TAG:-dev}
    build: ./api
    ports:
      - 8571:80
    environment:
      POSTGRES_URL: postgres://postgres:<<database-password>>@postgres/postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: <<database-password>>
      POSTGRES_USER: postgres
    volumes:
      - ./.db/postgres:/var/lib/postgresql/data
      - ./db/pg_hba.sh:/docker-entrypoint-initdb.d/pg_hba.sh
      - ./db/postgres.conf:/etc/postgres.conf
    ports:
      - 5432:5432
    command: postgres --config_file=/etc/postgres.conf

