[package]
name = "api"
version = "0.1.0"
authors = ["Emil Broman <emil@emilbroman.me>"]
edition = "2018"

[dependencies]
juniper = "0.14.2"
juniper_rocket = "0.5.2"
rocket = "0.4"
log = "0.4.8"
uuid = { version = "0.8", features = ["v4"] }
