apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspen-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: docker.pkg.github.com/aspen-lang/platform/api:latest
        ports:
        - containerPort: 80
