name: Push to Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: aspen-lang
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker

      - name: Set Docker Tag Environment Variables
        uses: allenevans/set-env@v1.0.0
        with:
          API_TAG: ${{ hashFiles('api/**') }}
          API_SERVICE_NAME: aspen-api-staging
          CACHE_TAG: staging

      - name: Build and Deploy
        run: make pull push


