name: Push to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: aspen-lang
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker

      - uses: allenevans/set-env@v1.0.0
        with:
          API_TAG: ${{ hashFiles('api/**') }}

      - run: make pull
      - run: make push


